title: Levi Sprung
baseURL: levibsprung.github.io
languageCode: en-us
theme: mini
defaultContentLanguage: en
# disqusShortname: your-disqus-shortname

social:
  github: https://github.com/levibsprung/
  spotify: https://open.spotify.com/user/9c7y9lzudp57ixe94b0ajr3ux?si=e912596ebc36460a
  linkedin: https://www.linkedin.com/in/levi-sprung
  email: mailto:levibsprung@gmail.com



params:
  author: Levi Sprung
  bio: Aspiring Software Engineer and Data Scientist
  description: Personal website and blog
  links:
    - name: testLink
      url: https://example.com
# googleAnalytics: your-google-analytics-id


